### ISSUE TITLE
Typos and general things

### ISSUE THREAD

**Issue by arsenvlad** [CJLove/SM_Cluster#1]
SSHCredntials
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/createUiDefinition.json#L15

https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/createUiDefinition.json#L186

Required smSiteID cannot be 0 characters in length.
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/createUiDefinition.json#L66

smPassword and smRESTPassword is this regex correct?
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/createUiDefinition.json#L97

and

https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/createUiDefinition.json#L80

Does the min count of consecutive IP addresses need to be 5 + VM count?
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/createUiDefinition.json#L150

The NSG entry will not be applicable for the "real template" since would lead to too many failures without special NSG UI control (which we don't yet have)
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/createUiDefinition.json#L159

**Comment by CJLove** [comment]
- SSHCredntials fixed.
- Changed SiteID to required="false"
- Fixed the constraint for consecutive IP addresses

**Comment by CJLove** [comment]
Following what has been done with the Teradata templates we will likely need an "Internal" version of this template for use internally which does prompt for the NSG and an external one which creates an NSG.

**Comment by CJLove** [comment]
For smAdminPassword and smRESTPassword the regex is correct, the tooltip was inaccurate.
