### ISSUE TITLE
Add allowedValues to vnetNewOrExisting parameter

### ISSUE THREAD

**Issue by arsenvlad** [CJLove/SM_Cluster#2]
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/mainTemplate.json#L62

add allowedValues with values new and existing similar to this
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/mainTemplate.json#L27

**Comment by CJLove** [comment]
Fixed.
