### ISSUE TITLE
Don't specify defaultValue if parameter is required

### ISSUE THREAD

**Issue by arsenvlad** [CJLove/SM_Cluster#3]
Since these two passwords are required (I am assuming) remove defaultValue: "" from them
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/mainTemplate.json#L141

https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/mainTemplate.json#L148

Default Value of empty is used on the admin password because that can be empty when user selects SSH Public Key authentication approach.

**Comment by CJLove** [comment]
Fixed.
