### ISSUE TITLE
Specify the public IP of the VM (if any) in the outputs

### ISSUE THREAD

**Issue by arsenvlad** [CJLove/SM_Cluster#4]
Seems like outputs are empty https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/mainTemplate.json#L324

For user convenience, output fqdn similar to this
https://github.com/arsenvlad/azure-lustre-from-image/blob/5faa91b8ffc5e835120bf55b8126a2ceb17c72cd/mainTemplate.json#L866

**Comment by CJLove** [comment]
Added output of first SM VM's fqdn and URL for SM Web Interface.

**Comment by CJLove** [comment]
Closing.  Output is now visible in the portal following successful deployment.
