### ISSUE TITLE
publicIP-multiple.json and publicIP-single.json

### ISSUE THREAD

**Issue by arsenvlad** [CJLove/SM_Cluster#5]
It seems like these two files are not used https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/publicIP-multiple.json

https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/publicIP-single.json

I see that you always assign new publicIPs to the SM VMs here: 
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/serverManagement.json#L259

So you can probably remove the publicIP...json files to avoid confusion.

**Comment by CJLove** [comment]
These may be leftovers from the ecosystem solution template.  You're correct in that the SM VMs are each getting public IPs assigned.  Files removed (at least for now).
