### ISSUE TITLE
How are you passing user inputs to inside of the VM?

### ISSUE THREAD

**Issue by arsenvlad** [CJLove/SM_Cluster#7]
How are you passing user inputs like smPassword, smRESTPassword, etc. to the VM?

It looks like the commandToExecute does not take these as parameters:
https://github.com/CJLove/SM_Cluster/blob/879deaa0175c44aa2ffab3f3f5c60012550a2b13/serverManagement.json#L384

So the user entries would not be used anywhere.

**Comment by CJLove** [comment]
The current call to 'tdc-ecossh --enable' is a placeholder.  Once I have a VM image supporting it those parameters will be passed in to a different custom script.

**Comment by CJLove** [comment]
Template updated to call cmic-cloud-config with base IP address, smSystemCount, smAdminPassword, smRESTPassword, and smSiteID
